# Utiliza la imagen oficial de Node 20 como base
FROM node:20

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copialos archivos del proyecto desde la carpeta frontend al directorio de trabajo en el contenedor
COPY frontend/ .

# Instala las dependencias del proyecto
RUN npm install

# Expone el puerto 3000 para acceder a la aplicación React
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["npm", "start"]
