version: '3.8'

services:
  clasificador:
    build:
      context: .
      dockerfile: Dockerfile.clasificador
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=pass
      - DB_NAME=proyecto

  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

