# Utiliza una imagen oficial de Python como base
FROM python:3.9

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos del proyecto al directorio de trabajo en el contenedor
COPY clasificador/ .

# Instala las dependencias del proyecto
RUN pip install --upgrade pip
RUN pip install -r requirements.txt