/*insertar datos usuers*/
INSERT INTO users (firstname, lastname, email, username, password) VALUES
('Keila', 'Cortez', 'keila.cor@example.com', 'kcortez', 'password123'),
('Tito', 'Fajardo', 'tito.fajardo@example.com', 'tfajardo', 'password123'),
('Edwin', 'Hilario', 'edhilario@example.com', 'ehilario', 'password123'),
('Eber', 'Guerra', 'eber.guerra@example.com', 'eguerra', 'password123'),
('Sergio', 'Apellido', 'sergio@example.com', 'sergio', 'password123'),
('David', 'Wilson', 'david.wilson@example.com', 'davidwilson', 'password123'),
('Eve', 'Taylor', 'eve.taylor@example.com', 'evetaylor', 'password123'),
('Frank', 'Anderson', 'frank.anderson@example.com', 'frankanderson', 'password123'),
('Grace', 'Thomas', 'grace.thomas@example.com', 'gracethomas', 'password123'),
('Hank', 'Lee', 'hank.lee@example.com', 'hanklee', 'password123');


/*Insertar movies del csv*/
INSERT INTO movies (movie_title, movie_info, genres, directors, authors, actors, streaming_release_date, runtime, production_company, tomatometer_status, tomatometer_rating, tomatometer_count) 
VALUES 
('m/0814255 Percy Jackson & the Olympians: The Lightning Thief', 'Always trouble-prone, the life of teenager Percy Jackson (Logan Lerman) gets a lot more complicated when he learns he\'s the son of the Greek god Poseidon. At a training ground for the children of deities, Percy learns to harness his divine powers and prepare for the adventure of a lifetime: he must prevent a feud among the Olympians from erupting into a devastating war on Earth, and rescue his mother from the clutches of Hades, god of the underworld.', 'Action & Adventure, Comedy, Drama, Science Fiction & Fantasy', 'Chris Columbus', 'Craig Titley, Chris Columbus, Rick Riordan', 'Logan Lerman, Brandon T. Jackson, Alexandra Daddario, Jake Abel, Sean Bean, Pierce Brosnan, Steve Coogan, Rosario Dawson, Melina Kanakaredes, Catherine Keener, Kevin Mckidd, Joe Pantoliano, Uma Thurman, Ray Winstone, Julian Richings, Bonita Friedericy, Annie Ilonzeh, Tania Saulnier, Marie Avgeropoulos, Luisa D\'Oliveira, Christie Laing, Marielle Jaffe, Elisa King, Chrystal Tisiga, Alexis Knapp, Charlie Gallant, Chelan Simmons, Andrea Brooks, Natassia Malthe, Max Van Ville, Serinda Swan, Dimitri Lekkos, Ona Grauer, Stefanie von Pfetten, Conrad Coates, Erica Cerra, Dylan Neal, Luke Camilleri, Holly Hougham, Ina Geraldine, Raquel Riskin, Yusleidis Oquendo, Janine Edwards, Valerie Tian, Violet Columbus, Sarah Smyth, Merritt Patterson, Julie Luck, Andrea Day, John Stewart, Suzanne Ristic, Deejay Jackson, Matthew Garrick, Stan Carp, Suzanna Ristic, Richard Harmon, Maria Olsen, Robin Lemon, Doyle Devereux, Tom Pickett, VJ Delos-Reyes, Tim Aas, Keith Dallas, Spencer Atkinson, Maya Washington, Loyd Bateman, Victor Ayala, Zane Holtz, Eli Zagoudakis, Matt Reimer, Rob Hayter, Lloyd Bateman, Shawn Beaton, Jarod Joseph, Reilly Dolman, Paul Cummings, Julie Brar, Dejan Loyola, Damian Arman, Mario Casoria, Dorla Bell, Carolyn Adair (II), Jade Pawluk, G. Patrick Currie, Darian Arman, Mariela Zapata, David L. Smith', '2015-11-25', 119, '20th Century Fox', 'Rotten', 4.9, 149),
('m/0878835 Please Give', 'Kate (Catherine Keener) and her husband Alex (Oliver Platt) are wealthy New Yorkers who prowl estate sales and make a tidy profit reselling items they bought cheaply. They buy the apartment next door and plan to remodel just as soon as its current occupant, a cranky old woman, dies. Kate is troubled by the way she and her husband earn a living, and tries to assuage her guilt by befriending her tenant and the woman\'s granddaughters, but her overtures lead to unexpected consequences.', 'Comedy', 'Nicole Holofcener', 'Nicole Holofcener', 'Catherine Keener, Amanda Peet, Oliver Platt, Rebecca Hall, Sarah Steele, Ann Morgan Guilbert, Kevin Corrigan, Lois Smith', '2012-09-04', 90, 'Sony Pictures Classics', 'Certified-Fresh', 8.7, 142),
('m/10 10', 'A successful, middle-aged Hollywood songwriter falls hopelessly in love with the woman of his dreams, and even follows the girl and her new husband to their Mexican honeymoon resort. While his behavior seems sure to land him in trouble, out of the blue fate plays into his hands.', 'Comedy, Romance', 'Blake Edwards', 'Blake Edwards', 'Dudley Moore, Bo Derek, Julie Andrews, Robert Webber, Dee Wallace, Sam Jones III, Sam J. Jones, Brian Dennehy, Max Showalter, Rad Daly, Nedra Volz, James Noble, Virginia Kiser, John Hawker, Deborah Rush, Don Calfa, Walter George Alton, Annette Martin, John Hancock, Lorry Goldman, Arthur Rosenberg, Mari Gorman, Marcy Hanson, Julia Jennings, Senilo Tanney, Kitty DeCarlo, William Lucking, Owen Sullivan, Debbie White, Laurence Carr, Camila Ashland, Adrian Aron, Gail Bowman, Burke Byrnes, Michael Champion, Doug Sheehan, J. Victor Lopez, Gregory Chase, Jon Linton, Ellen Clark, Antonia Ellis, John Chappell, Lynn Farrell, Art Kassul, Denise Crosby, Jeanetta Arnette', '2014-07-24', 122, 'Waner Bros.', 'Fresh', 6.7, 24),
('m/1000013-12_angry_men 12 Angry Men (Twelve Angry Men)', 'Following the closing arguments in a murder trial, the 12 members of the jury must deliberate, with a guilty verdict meaning death for the accused, an inner-city teen. As the dozen men try to reach a unanimous decision while sequestered in a room, one juror (Henry Fonda) casts considerable doubt on elements of the case. Personal issues soon rise to the surface, and conflict threatens to derail the delicate process that will decide one boy\'s fate.', 'Classics, Drama', 'Sidney Lumet', 'Reginald Rose', 'Martin Balsam, John Fiedler, Lee J. Cobb, E.G. Marshall, Jack Klugman, Edward Binns, Jack Warden, Henry Fonda, Joseph Sweeney, Ed Begley Sr., George Voskovec, Robert Webber, Rudy Bond, James A. Kelly, Billy Nelson, John Savoca', '2017-01-13', 95, 'Criterion Collection', 'Certified-Fresh', 10, 54),
('m/1000204-abraham_lincoln Abraham Lincoln', 'The 16th U.S. president (Walter Huston) is portrayed as a lawyer, orator, husband and Civil War commander.', 'Classics, Drama', 'D.W. Griffith', 'Gerrit J. Lloyd, Stephen Vincent Benét', 'Walter Huston, Una Merkel, Kay Hammond, Ian Keith, Jason Robards Sr., E. Alyn Warren, Hobart Bosworth, Fred Warren, Henry B. Walthall, Frank Campeau, Francis Ford, William L. Thorne, Lucille La Verne, Helen Freeman, Oscar Apfel, Otto Hoffman, Edgar Dearing, Russell Simpson, Helen Ware, Charles Crockett, Jason Robards Sr., Gordon Thorpe, James Bradbury Sr., Cameron Prud\'Homme, James Eagles, Hank Bell, James Bradbury Jr, Carl Stockdale, George MacQuarrie, Ralph Lewis, Mary Forbes, Robert E. Homans', '2013-12-03', 97, 'United Artists', 'Fresh', 8.2, 11),
('m/10002114-dark_water Dark Water', 'In this moody Japanese horror film, newly-single mom Yoshimi Matsubara (Hitomi Kuroki) is enduring a bitter divorce and struggling to keep custody of her young daughter, Ikuko (Rio Kanno). As the unstable Yoshimi tries to make a fresh start in a new apartment, strange occurrences in the building gradually begin to take their toll. When Yoshimi and Ikuko both start seeing unsettling visions of a ghostly little girl, it\'s clear that they\'re being drawn toward the supernatural.', 'Art House & International, Horror, Mystery & Suspense', 'Hideo Nakata', 'Hideo Hakata, Takashige Ichise, Yoshihiro Nakamura, Ken-ichi Suzuki', 'Hitomi Kuroki, Rio Kanno, Shigemitsu Ogi, Mirei Oguchi, Asami Mizukawa, Yu Tokui, Fumiyo Kohinata, Isao Yatsu', '2017-03-23', 100, 'Toho Company Ltd', 'Fresh', 8.0, 15),
('m/1000224-accused The Accused', 'Out drinking one night after a fight with her boyfriend, Sarah Tobias (Jodie Foster) is brutally raped by three men in a bar while people watch and cheer. District Attorney Kathryn Murphy (Kelly McGillis) takes the case, however allows the rapists to receive a mild sentence. A distraught Sarah decides to seek punishment for the men who witnessed and encouraged the rape. To get justice, Sarah must take the stand and revisit the night of her attack in this drama based on true events.', 'Drama, Mystery & Suspense', 'Jonathan Kaplan', 'Tom Topor', 'Jodie Foster, Kelly McGillis, Bernie Coulson, Leo Rossi, Ann Hearn, Steve Antin, Tom O\'Brien, Allan Lysell, Carmen Argenziano, Terry David Mulligan, Woody Brown, Peter Van Norden, Scott Paulin, Kim Kondrashoff, Stephen E. Miller, Andrew Kavadas, Tom McBeath, Rose Weaver, Linda Darlow, Veena Sood, Anthony Holland, Kevin McNulty, Jerry Wasserman, Barney O\'Sullivan, Christianne Hirt, Frances Flanagan, Mike Winlaw, Deryl Hayes, Dana Still, Denalda Williams, Babs Chula, Rebecca Toolan, Stephen Dimopoulos, Freda Perry, Dave Sheridan, Gary Chalk, Garwin Sanford, Gloria Lee, Michelle Goodger, Thomas Heaton, Pamela Sue Martin, Wally Marsh', '2016-10-04', 110, 'Paramount Pictures', 'Fresh', 9.1, 22),
('m/10002516-lost_city The Lost City', 'Fico Fellove (Andy Garcia), an apolitical Havana club owner, gets caught in the middle when Fidel Castro\'s Communist Revolution sweeps through Cuba. He tries to keep the strife outside the walls of his popular establishment, but his family becomes divided when his brothers (Nestor Carbonell, Enrique Murciano) join the fight against Batista.', 'Drama', 'Andy Garcia', 'G. Cabrera Infante, Guillermo Cabrera Infante', 'Andy Garcia, Dustin Hoffman, Bill Murray, Inés Sastre, Tomás Milian, Elizabeth Peña, Jsu Garcia, Nestor Carbonell, Lorena Feijoo, Millie Perkins, Enrique Murciano Jr., Richard Bradford, Dominik García-Lorido, Steven Bauer, Tony Plana, Juan Fernández, Sergio Carlo, William Marquez, Julio Oscar Mechoso, Daniel Pino, Ruben Rabasa, Victor Rivers, Waldemar Kalinowski', '2017-03-23', 143, 'Magnolia Pictures', 'Rotten', 2.5, 83),
('m/10002519-breaking_point The Breaking Point', 'A charter-boat captain winds up in the middle of a syndicate shootout after transporting illegal immigrants.', 'Drama', 'Michael Curtiz', 'Ranald MacDougall', 'John Garfield, Patricia Neal, Phyllis Thaxter, Juano Hernandez, Wallace Ford, Edmon Ryan, Ralph Dumke, Guy Thomajan, William Campbell, Sherry Jackson, Donna Jo Boyce, Victor Sen Yung, Peter Brocco, John Doucette, James Griffith, Norman Field, Juan Duval, Spencer Chan, Helen Hatch, Bob McLean, Beverly Mook, John Close, Alex Gerry, Mary Carroll, Glen Turnbull, John Chapin Morgan, John Alvin, David McMahon, Paul McGuire, Len Hendry', '2016-08-25', 97, 'Warner Home Video', 'Fresh', 10.0, 10),
('m/10003276-criminal Criminal', 'Needing a new partner capable of intricate cons, Richard Gaddis (John C. Reilly), recruits Rodrigo (Diego Luna), a crook with a perfect poker face. The two plan a big-time scam: selling a fake Silver Certificate to currency collector William Hannigan (Peter Mullan). Rodrigo distrusts his new associate, but needs money to help out his ill father. The situation becomes more complicated when Rodrigo falls for Gaddis\' sister, Valerie (Maggie Gyllenhaal), drawing another player into the game.', 'Drama, Mystery & Suspense', 'Greggory Jacobs, Gregory Jacobs, Greg Jacobs', 'Gregory Jacobs, Fabián Bielinsky, Steven Soderbergh, Sam Lowry, Greggory Jacobs, Greg Jacobs', 'John C. Reilly, Diego Luna, Maggie Gyllenhaal, Jonathan Tucker, Peter Mullan, Zitto Kazann, Maeve Quinlan, Laura Cerón, Soledad St. Hilaire, Brandon Keener, Gary Mack, Ellen Geer, Brent Sexton, Enrico Colantoni, Nick Anavio, Deborah Van Valkenburgh, Malik Yoba, Lillian Hurst, Jack Conley, Juan Carlos Cantu, Manuel G. Jimenez, Luis Contreras, Patricia Belcher, Paul Norwood', '2016-04-27', 87, 'Warner Bros. Pictures', 'Fresh', 6.9, 124),
('m/1000334-adventures_of_mark_twain The Adventures of Mark Twain', 'In this claymation film, celebrated author Mark Twain (James Whitmore), displeased with the state of humanity, sets off in a hot-air balloon to meet his celestial destiny: Halley\'s Comet. Stowed away on the craft are beloved characters from Twain\'s stories -- Tom Sawyer (Chris Ritchie), Becky Thatcher (Michele Mariana) and Huckleberry Finn (Gary Krug). As Twain\'s balloon ascends ever higher to its ultimate goal, his literary creations try to persuade him of the essential goodness of man.', 'Action & Adventure, Animation, Kids & Family', 'Will Vinton', 'Susan Shadburne', 'James Whitmore, Michele Mariana, Gary Krug, Chris Ritchie, Carol Edelman, John Hennigan', '2017-02-04', 86, 'Eureka Entertainment Ltd', 'Fresh', 8.0, 5),
('m/10003437-deep_blue Deep Blue', 'This nature documentary shows the lives of different animals in and near the oceans that make up two-thirds of the planet\'s surface. Gray whales make their migratory journeys despite being menaced by killer whiles, while smaller fish struggle to stay alive. In the Arctic, penguins and polar bears endure the winter, while on beaches crabs emerge to feed. Meanwhile, five miles under the water, unusual forms of life thrive -- many of them in places less explored than the moon.', 'Documentary, Special Interest', 'Andy Byatt, Alastair Fothergill', 'Alastair Fothergill, Andy Byatt, Tim Ecott', 'Pierce Brosnan, Michael Gambon', '2016-12-07', 90, 'Miramax Flims', 'Fresh', 6.7, 52),
('m/1000355-adventures_of_robin_hood The Adventures of Robin Hood', 'When King Richard the Lionheart is captured, his scheming brother Prince John (Claude Rains) plots to reach the throne, to the outrage of Sir Robin of Locksley (Errol Flynn), the bandit king of Sherwood Forest. Rounding up his band of men and eventually winning the support of the lovely Maid Marian (Olivia de Havilland), Robin accuses Prince John of treachery and, when the escaped Richard returns covertly to England, joins forces with the king to prevent Prince John from taking the crown.', 'Action & Adventure, Classics, Romance', 'Michael Curtiz, William Keighley', 'Norman Reilly Raine, Seton I. Miller, Michael Curtiz, William Keighley', 'Errol Flynn, Olivia de Havilland, Basil Rathbone, Claude Rains, Eugene Pallette, Alan Hale, Una O\'Connor, Patric Knowles, Melville Cooper, Herbert Mundin, Montagu Love, Ian Hunter, Robert Warwick, Leonard Willey, Harry Cording, Howard Hill, Robert Noble, Kenneth Hunter, Colin Kenny, Lester Matthews, Ivan Simpson, James Baker, Charles McNaughton, Wilfred Lucas, Lionel Belmore, Janet Shaw, Reginald Sheffield, Crauford Kent, Austin Fairman, Hal Brazeale, Holmes Herbert, Leonard Mudie, Herbert Evans, Alec Harford, Peter Hobbes, Leyland Hodgson, Olaf Hytten, Marten Lamont, Val Stanton, John Sutton', '2014-01-23', 102, 'Warner Bros.', 'Certified-Fresh', 10.0, 48),
('m/10003876-man_hunt Man Hunt', 'Renowned big-game hunter Captain Thorndike (Walter Pidgeon) is hunting in the Bavarian forest when he stumbles upon Adolf Hitler\'s vacation residence. Tempted by the idea of assassinating the dictator, he\'s apprehended and beaten before escaping and stowing away on a steamship back to England. Onboard, Thorndike has his identity stolen by the smooth-talking con man Mr. Jones (John Carradine). Both men soon discover that Gestapo agents are swarming London, looking for the would-be assassin.', 'Classics, Drama, Mystery & Suspense', 'Fritz Lang', 'Dudley Nichols', 'Walter Pidgeon, Joan Bennett, George Sanders, John Carradine, Roddy McDowall, Ludwig Stossel, Heather Thatcher, Frederic Worlock, Roger Imhof, Egon Brecher, Holmes Herbert, Fredrik Vogeding, Lucien Prival, Herbert Evans, Edgar Licho, Eily Malyon, John Rogers, Lester Matthews, Arno Frey, Keith Hitchcock, Walter Bonn, Otto Reichow, Robert Stephenson, William Haade, Adolph Milar, Sven Hugo Borg, Hans Joby, Douglas Gerrard, Clifford Severn, Charles Bennett, Bobby Hale, Frank Benson, Cyril Delevanti, Bruce Lister, Carl Ekberg, Olaf Hytten, William Von Brincken, Virginia McDowall, Bruce Lester, Richard Fraser, Kurt Kreuger', '2014-03-01', 100, 'Twentieth Century Fox', 'Fresh', 9.2, 12);


/*reviews de usuarios*/
INSERT INTO user_reviews (id_user, id_movie, review_score, review_content, review_status, review_date) 
VALUES 
(1, 1, 8.5, 'A captivating drama with a twisty plot and strong performances.', 'Rotten', '2024-05-21'),
(1, 3, 7.2, 'An enjoyable animation with a heartwarming message.', 'Fresh', '2024-05-20'),
(1, 2, 9.0, 'A visually stunning documentary showcasing the beauty of the ocean.', 'Rotten', '2024-05-19'),
(2, 1, 8.0, 'A classic adventure film with exciting action sequences.', 'Fresh', '2024-05-18'),
(3, 5, 7.5, 'A gripping suspense film with strong performances from the cast.', 'Rotten', '2024-05-17'),
(4, 6, 6.5, 'Disappointing plot twists and lackluster acting.', 'Fresh', '2024-05-16'),
(5, 7, 8.8, 'A charming animation that appeals to both children and adults.', 'Rotten', '2024-05-15'),
(6, 1, 7.0, 'Informative documentary but lacks a compelling narrative.', 'Fresh', '2024-05-14'),
(7, 2, 9.5, 'A timeless classic with memorable characters and thrilling adventure.', 'Fresh', '2024-05-13'),
(2, 3, 8.2, 'Suspenseful and engaging from start to finish.', 'Rotten', '2024-05-12');


